language: ruby
rvm:
  - 3.3.5
env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite
install:
  - bundle install
script:
  - cd spec/dummy && RAILS_ENV=test bundle exec rake db:create db:schema:load && cd ../..
  - bundle exec rspec
