# frozen_string_literal: true

require_relative "boot"

require "rails/all"

Bundler.require(*Rails.groups)
require "active_reporter"

module Dummy
  class Application < Rails::Application
    # Initialize configuration defaults for the Rails version in use.
    config.load_defaults 8.1

    # This dummy app only exists to exercise the gem's specs; it has no HTTP
    # surface, so the framework config generated by `rails new` is intentionally
    # left at the loaded defaults above. Settings in config/environments/* and
    # config/initializers/* take precedence over anything specified here.
  end
end
